---
title: "fdas"
author: "Billy McGloin"
date: "2023-10-13"
output: html_document
---

```{r}
library(tidyverse)
```


```{r}
# let's load in the data
nova2122 <- read.csv('./data/raw_data/villanova2122.csv')
```

```{r}
# let's check the shape of the data
dim(nova2122)
```

```{r}
# what are the column names?
colnames(nova2122)
```

```{r}
# this data looks relatively clean, but we want only shooting data
# let's get rid of rows where there isn't a shooter
# this would be rows where the shooter is NA
# such as a turnover, steal, rebound, or block
nova2122 <- nova2122 %>%
  filter(!is.na(shooter))

# let's check the shape of the data
dim(nova2122)
```


```{r}
your_tibble <- your_tibble %>%
  arrange(game_id, play_id) %>%
  group_by(shooter, game_id) %>%
  mutate(
    previous_shots = ifelse(
      shot_outcome == "missed",
      cumsum(shot_outcome == "made" & lag(shot_outcome, default = "") == "missed") - cumsum(shot_outcome == "missed" & lag(shot_outcome, default = "") == "made"),
      ifelse(shot_outcome == "made", cumsum(shot_outcome == "made" & lag(shot_outcome, default = "") == "missed") - cumsum(shot_outcome == "missed" & lag(shot_outcome, default = "") == "made"), 0)
    )
  ) %>%
  ungroup() %>%
  arrange(game_id, play_id)
```

