---
title: "Introduction"
format: html
toc: true
bibliography: references.bib
---

<b>*Disclaimer - this section is a work in progress</b>

# Introduction to the Hot Hand

Within the world of sports, the terms “hot hand” or being “in the zone” are frequently used to describe a streak of exceptional performance by a player. The “hot hand” term originated in the sport of basketball, suggesting that a player who has made numerous successive shots is more likely to make their next basket, as opposed to the same person who had missed their last few shots. For example, a basketball player may make an exceptional number of shots in a short period of time, such as Klay Thompson scoring 37 points in a quarter. Another example is Joe DiMaggio’s 56 game hitting streak in 1941, one of the most incredible hitting runs in baseball history. Ordinarily, these types of “runs” or “streaks” are rare. There is “a belief that the performance of a player during this particular period is significantly better than expected on the basis of the player’s overall record” [^1]. Often, this heightened performance can be attributed to increased confidence by the player. 
<br></br>
This belief is shared by a majority of players, coaches, and fans, yet there is little statistical evidence to support this phenomenon. In fact, a majority of studies suggest that the “hot hand” is a fallacy and advise coaches not to consider it when selecting plays. The “hot hand” phenomenon has been studied by many psychologists and statisticians who still debate this issue to this day. 
<br></br>
While the term “hot hand” may be most commonly associated with the world of sports, “studies have been done in other academic fields outside the sports domain, such as economics and cognitive science” [^2]. Through this project, I plan to explore the mystery of streaks both within and outside the world of sports.


[^1]: @gilovich1985hot

[^2]: @bar2006twenty

## Prior Research

The initial investigation into this topic @gilovich1985hot was published in 1985. It analyzed assorted data, including professional basketball field goal data from the 1980-1981 season, professional basketball free-throw data from the 1980-1982 seasons, and a controlled shooting experiment. While the study found that over 91% of fans agreed that a player has a better chance of making a shot after having just made his last two or three shots than he does after having just missed his last two or three shots, none of their data showed any evidence of this phenomenon. Instead, @gilovich1985hot argued that there is a wide-spread misperception of random sequences:

> People’s intuitive conceptions of randomness depart systematically from the laws of chance. It appears that people expect the essential characteristics of a chance process to be represented not only globally in the entire sequences, but also locally, in each of its parts. For instance, people expect even short sequences of heads and tails to reflect the fairness of a coin and contain roughly 50% heads and 50% tails. This conception of chance has been described as a ‘belief in the law of small numbers’ according to which the law of large numbers applies to small samples as well. A locally representative sequence, however, deviates systematically from chance expectation: It contains too many alternations and not enough long runs.

@bar2006twenty published a review and critique of 20 years of “hot hand” research in 2006. This paper reviewed the @gilovich1985hot study in addition to subsequent research that used data from various sports including basketball, baseball, golf, darts, tennis, bowling, and more. Baseball and basketball studies dominate the literature on this subject, yet the strongest support for the “hot hand” can be found in more individual sports such as horseshoe pitching and tennis. 

> Demonstrations of hot hands per se are rare and often weak, due to various reasons: using and unrealistic model and questionable data, setting questionable definitions for hot and cold players, relating streakiness to difficulty of task, combining and analyzing data of all players a as a group, and other constraints related to the kind of sport studied.

In the end, this study found that the question remains unresolved. 
<br></br>
<b>MORE RESEARCH TO COME</b>

## The Debate

<b>MORE TO BE ADDED</b>

## 10 Questions

1. What data is available for my topic? 
2. What does current literature on the topic argue?
3. How can I build off of the current research and approach the topic in a novel way?
4. Should I limit the scope of my topic to sports or can I expand past that? 
5. How should I define success? (the concept of the hot hand is that success breeds success)
6. What is the best way to visualize the data? 
7. Do athletes and/or the public believe in this phenomenon? 
8. Is there any evidence that the hot hand exists?
9. Does the hot hand impact strategy of a game? Should it impact strategy? 
10. If the hot hand does exist, in what sport (or area outside of sports) is there the most evidence in support of the phenomenon? 

## Goals and Hypothesis

1. I would love to find some evidence that the hot hand exists
2. 